export APP_YOUTUBEDL_IP="10.21.25.9"
export APP_YOUTUBEDL_PORT="17442"

YOUTUBEDL_TOR_DIR="${EXPORTS_TOR_DATA_DIR}/app-${EXPORTS_APP_ID}"
mkdir -p "${YOUTUBEDL_TOR_DIR}"
touch "${YOUTUBEDL_TOR_DIR}/hostname"